todo/urls.py
from django.urls import path

from .views import TaskTemplateView, TaskUpdateView, ListTasksView, TaskDeleteView

urlpatterns = [
    path('', TaskTemplateView.as_view(), name='home'),
    path('api/<int:pk>/', TaskUpdateView.as_view(), name='update-task'),
    path('api/<int:pk>/delete/', TaskDeleteView.as_view(), name='delete-task'),
    path('api/', ListTasksView.as_view(), name='list-task'),
]

blog/models.py
import uuid
from datetime import datetime

from django.conf import settings
from django.core.mail import EmailMessage
from django.db import models
from django.utils.timezone import now
from django.utils.translation import gettext as _

from taggit.managers import TaggableManager
from taggit.models import GenericUUIDTaggedItemBase, TaggedItemBase

from project.utils import generate_unique_slug
from users.models import User
from .choices import *

class UUIDTaggedItem(GenericUUIDTaggedItemBase, TaggedItemBase):

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

def default_intro():
    return _('Another article by %(name)s!') % {'name': settings.WEBSITE_NAME}

class Article(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    slug = models.SlugField(max_length=50, editable=False, null=True)
    title = models.CharField(_('Title'),
        help_text=_("The title of the article"),
        max_length = 50)
    intro = models.CharField(_('Introduction'),
        default = default_intro,
        max_length = 100)
    body = models.TextField(_('Text'), null=True)
    date = models.DateField(_('Date'), default = now, )
    last_updated = models.DateTimeField(editable=False, null=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL,
        blank= True, null=True, verbose_name = _('Author'))
    tags = TaggableManager(verbose_name=_("Categories"),
        help_text=_("Comma separated list of categories"),
        through=UUIDTaggedItem, blank=True)
    notice = models.CharField(max_length = 4, choices = NOTICE,
        blank = True, null = True, verbose_name = _('Notify by email'),
        help_text = _("""Send automatic notification by selecting
            'Send notification' and saving the article.
            """))

    def get_path(self):
        temp = self.date
        #conditional added for test to work
        if isinstance(temp, str):
            temp = temp.split(' ')[0]
            temp = datetime.strptime(temp, '%Y-%m-%d')
        return _('/articles/') + temp.strftime("%Y/%m/%d") + '/' + self.slug

    def get_uploads(self):
        return self.article_uploads.all()

    def get_tags(self):
        return list(self.tags.names())

    def get_previous(self):
        try:
            return self.get_previous_by_date()
        except Article.DoesNotExist:
            return

    def get_next(self):
        try:
            return self.get_next_by_date()
        except Article.DoesNotExist:
            return

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = generate_unique_slug(Article, self.title)
        self.last_updated = now()
        if self.notice == 'SPAM':
            message = self.title + '\n'
            message += self.intro + '\n'
            url = settings.BASE_URL + self.get_path()
            message += _('Follow this link to read it: ') + url + '\n'
            recipients = User.objects.filter( is_active = True, )
            #inactive users may not have profile
            recipients = recipients.filter( profile__yes_spam = True, )
            mailto = []
            for recipient in recipients:
                mailto.append(recipient.email)
            subject = _('New article on %(name)s ') % {'name': settings.WEBSITE_NAME}
            email = EmailMessage(subject, message, settings.SERVER_EMAIL,
                mailto)
            email.send()
            self.notice = 'DONE'
        super(Article, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Article')
        verbose_name_plural = _('Articles')
        ordering = ('-date', )

class UserUpload(models.Model):
    post = models.ForeignKey(Article, on_delete = models.CASCADE,
        null = True, related_name='article_uploads')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null = True,
        verbose_name = _('User'))
    date = models.DateTimeField(_('Date'), default = now, )
    image = models.ImageField(_('Image'), blank = True, null = True,
        upload_to = 'uploads/articles/users/',)
    body = models.CharField(_('Text'), help_text = _("Write something."),
        max_length=500 )

    def __str__(self):
        return _('Contribution - ') + str(self.id)

    class Meta:
        verbose_name = _('Contribution')
        verbose_name_plural = _('Contributions')
        ordering = ('-id', )

blog/forms.py
from django import forms
from django.forms import ModelForm
from django.utils.translation import gettext as _

from .models import UserUpload, Article
from users.models import User

class UserUploadForm(ModelForm):
    body = forms.CharField(label = _('Text'),
        widget=forms.Textarea(attrs={'placeholder': _("Leave here your message")}))
    class Meta:
        model = UserUpload
        fields = ('image', 'body',)

class ArticleForm(ModelForm):
    author = forms.ModelChoiceField(label=_("Author"), required = False,
        queryset = User.objects.filter(is_active = True, ).order_by('username'), )

    class Meta:
        model = Article
        fields = '__all__'

blog/api/views.py
from rest_framework.generics import ( ListCreateAPIView,
    RetrieveUpdateDestroyAPIView)
#from rest_framework.permissions import IsAuthenticated

from blog.models import Article
from .serializers import ArticleSerializer

class ArticleListCreateAPIView(ListCreateAPIView):
    queryset = Article.objects.all()
    #permission_classes = (IsAuthenticated, )
    serializer_class = ArticleSerializer
    lookup_field = 'uuid'

class ArticleRetrieveUpdateDestroyAPIView(RetrieveUpdateDestroyAPIView):
    queryset = Article.objects.all()
    #permission_classes = (IsAuthenticated, )
    serializer_class = ArticleSerializer
    lookup_field = 'uuid'

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import (ListView, DetailView, CreateView,
    TemplateView)
from django.views.generic.dates import (ArchiveIndexView, YearArchiveView,
    MonthArchiveView, DayArchiveView, )
from django.utils.crypto import get_random_string

from taggit.models import Tag

from users.models import User

from .forms import UserUploadForm
from .models import (UserUpload, Article,)
from .management.commands.fetch_article_emails import do_command

class TagMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        if 'tag' in self.request.GET:
            context['tag_filter'] = self.request.GET['tag']
        return context

    def get_queryset(self):
        qs = super().get_queryset()
        if 'tag' in self.request.GET:
            qs = qs.filter(tags__name=self.request.GET['tag'])
        return qs

class ArticleArchiveIndexView(TagMixin, ArchiveIndexView):
    model = Article
    date_field = 'date'
    allow_future = True
    context_object_name = 'posts'
    paginate_by = 12
    allow_empty = True

    def setup(self, request, *args, **kwargs):
        super(ArticleArchiveIndexView, self).setup(request, *args, **kwargs)
        do_command()

class ArticleYearArchiveView(TagMixin, YearArchiveView):
    model = Article
    make_object_list = True
    date_field = 'date'
    allow_future = True
    context_object_name = 'posts'
    paginate_by = 12
    year_format = '%Y'
    allow_empty = True

class ArticleMonthArchiveView(TagMixin, MonthArchiveView):
    model = Article
    date_field = 'date'
    allow_future = True
    context_object_name = 'posts'
    year_format = '%Y'
    month_format = '%m'
    allow_empty = True

class ArticleDayArchiveView(TagMixin, DayArchiveView):
    model = Article
    date_field = 'date'
    allow_future = True
    context_object_name = 'posts'
    year_format = '%Y'
    month_format = '%m'
    day_format = '%d'
    allow_empty = True

class DetailArticle(DetailView):
    model = Article
    context_object_name = 'post'
    slug_field = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #we add the following to feed standardized gallery
        context['main_gall_slug'] = get_random_string(7)
        context['title'] = self.object.title
        #gallery images
        context['images'] = self.object.article_image.all()

        return context

class UserUploadCreateView(PermissionRequiredMixin, CreateView):
    model = UserUpload
    form_class = UserUploadForm
    permission_required = 'blog.add_userupload'

    def get_success_url(self):
        if 'post_id' in self.request.GET:
            post = Article.objects.get(slug=self.request.GET['post_id'])
            return post.get_path() + '/#upload-anchor'
        return super(UserUploadCreateView, self).get_success_url(self)

    def form_valid(self, form):
        form.instance.user = self.request.user
        if 'post_id' in self.request.GET:
            form.instance.post = Article.objects.get(slug=self.request.GET['post_id'])
        return super(UserUploadCreateView, self).form_valid(form)

class AuthorListView(ListView):
    model = User
    #context_object_name = 'authors'
    template_name = 'blog/author_list.html'
    paginate_by = 10
    allow_empty = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        all_users = context['user_list']
        all_articles = Article.objects.all()
        all_contrib = UserUpload.objects.all()
        author_dict = {}
        for author in all_users:
            art_count = all_articles.filter(author_id = author.uuid).count()
            contrib_count = all_contrib.filter(user_id = author.uuid).count()
            if art_count or contrib_count:
                author_dict[author]=(art_count, contrib_count)
        context['authors'] = author_dict
        return context

class ByAuthorListView(ListView):
    model = Article
    context_object_name = 'posts'
    template_name = 'blog/article_archive_authors.html'
    paginate_by = 12
    allow_empty = True

    """We cannot subclass TagMixin because queryset is altered (by author), so
    the TagMixin snippets are included in get_queryset() and get() afterwards"""

    def get_queryset(self):
        qs = Article.objects.filter(author__username= self.kwargs['username'])
        if 'tag' in self.request.GET:
            qs = qs.filter(tags__name=self.request.GET['tag'])
        return qs

    def get(self, request, *args, **kwargs):
        super(ByAuthorListView, self).get(request, *args, **kwargs)
        context = self.get_context_data()
        context['author'] = get_object_or_404( User, username = kwargs['username'] )
        context['tags'] = Tag.objects.all()
        if 'tag' in self.request.GET:
            context['tag_filter'] = self.request.GET['tag']
        return self.render_to_response(context)

class ByUploadListView(ListView):
    model = UserUpload
    context_object_name = 'uploads'
    template_name = 'blog/uploads_by_author.html'
    paginate_by = 12
    allow_empty = True

    def get_queryset(self):
        qs = UserUpload.objects.filter(user_id__username= self.kwargs['username'])
        return qs

    def get(self, request, *args, **kwargs):
        super(ByUploadListView, self).get(request, *args, **kwargs)
        context = self.get_context_data()
        context['author'] = get_object_or_404( User, username = kwargs['username'] )
        return self.render_to_response(context)

blog/templates/blog/article_archive.html
{% extends 'blog/article_archive_tags.html' %}
{% load i18n %}

{% block title %}{{ website.acro }} | {% translate 'Articles' %}{% endblock title %}
{% block article_archive %}
<h4><strong>
  {% translate 'In-depth articles' %}
  {% if tag_filter %} {% translate 'in category:' %} {{ tag_filter|upper }}{% endif %}
</strong></h4>
{% include "blog/article_archive_list.html" %}
{% if is_paginated %}
  {% include "blog/article_pagination.html" %}
{% endif %}
{% endblock article_archive %}

blog/templates/blog/article_archive_authors.html
{% extends 'blog/article_archive_tags.html' %}
{% load i18n %}

{% block title %}{{ website.acro }} | {% translate 'Articles by' %} {{ author.get_full_name }}{% endblock title %}
{% block article_archive %}
<h4><strong>
  {% translate 'In depth articles by' %}
  {% if tag_filter %}
  <a href="{% url 'blog:post_by_author' author.username %}">{{ author.get_full_name }}</a>
  {% translate 'in category:' %} {{ tag_filter|upper }}
  {% else %}
  {{ author.get_full_name }}
  {% endif %}
</strong></h4>
{% include "blog/article_archive_list.html" %}
{% if is_paginated %}
  {% include "blog/article_pagination.html" %}
{% endif %}
{% endblock article_archive %}

blog/templates/blog/article_archive_day.html
{% extends 'blog/article_archive_tags.html' %}
{% load i18n %}

{% block title %}{{ website.acro }} | {% translate 'Articles of' %} {{ day }}{% endblock title %}
{% block article_archive %}
<h4><strong>
  {% translate 'Articles of' %} {{ day }}
  {% if tag_filter %} {% translate 'in category:' %} {{ tag_filter|upper }}{% endif %}
</strong></h4>
{% include "blog/article_archive_list.html" %}
<hr class="mb-4">
  <nav aria-label="Page navigation container">
  <ul class="pagination justify-content-center">
    {% if previous_day %}
    <li><a href="{% url 'blog:post_day' previous_day.year previous_day.month previous_day.day %}" class="page-link">&laquo; {% translate 'PREVIOUS' %} </a></li>
    {% endif %}
    {% if next_day %}
    <li><a href="{% url 'blog:post_day' next_day.year next_day.month next_day.day %}" class="page-link"> {% translate 'NEXT' %} &raquo;</a></li>
    {% endif %}
  </ul>
  </nav>
{% endblock article_archive %}

blog/templates/blog/article_archive_list.html
{% load fb_versions %}
{% load i18n %}

{% if posts %}
<div class="card-deck">
{% for post in posts %}
<div class="card" style="margin-bottom: 20px; min-width: 18rem;">
  <div class="card-header">
    <h4 class="card-title">
    <a href="{% url 'blog:post_detail' post.date.year post.date.month post.date.day post.slug %}">
      {{ post.title }}</a></h4>
  </div>
  {% if post.article_image.first %}
    <img class="card-img-top"
      src="{% version post.article_image.first.fb_image 'landscape' %}"
      alt="{{ post.intro }}">
  {% endif %}
  <div class="card-body">
    <em class="card-text">{{ post.intro }}</em>
    <ul class="list-inline">
      <li class="list-inline-item">
        {% if post.author %}
        <i class="fa fa-user" aria-hidden="true"></i>
        {{ post.author.get_full_name }}
        {% endif %}
      </li>
      <li class="list-inline-item">
        <i class="fa fa-calendar-o" aria-hidden="true"></i>
        {{ post.date|date:"d M Y" }}
      </li>
      {% if post.get_tags %}
        <li class="list-inline-item">
          <i class="fa fa-folder-open" aria-hidden="true"></i>
          {% for tag in post.get_tags %}
            {{ tag|upper }}
          {% endfor %}
        </li>
      {% endif %}
    </ul>
  </div>
</div>
{% endfor %}
</div>
{% else %}
<p>{% translate 'No articles available' %}</p>
{% endif %}

blog/templates/blog/article_archive_month.html
{% extends 'blog/article_archive_tags.html' %}
{% load i18n %}

{% block title %}{{ website.acro }} | {% translate 'Articles' %} {{ month|date:"M-Y" }}{% endblock title %}
{% block article_archive %}
<h4><strong>
  {% translate 'Articles of' %} {{ month|date:"M-Y" }}
  {% if tag_filter %} {% translate 'in category:' %} {{ tag_filter|upper }}{% endif %}
</strong></h4>
{% include "blog/article_archive_list.html" %}
<hr class="mb-4">
  <nav aria-label="Page navigation container">
  <ul class="pagination justify-content-center">
    {% if previous_month %}
    <li><a href="{% url 'blog:post_month' previous_month.year previous_month.month %}" class="page-link">&laquo; {% translate 'PREVIOUS' %} </a></li>
    {% endif %}
    {% if next_month %}
    <li><a href="{% url 'blog:post_month' next_month.year next_month.month %}" class="page-link"> {% translate 'NEXT' %} &raquo;</a></li>
    {% endif %}
  </ul>
  </nav>
{% endblock article_archive %}

blog/templates/blog/article_archive_tags.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
{% if tags %}
  <p>{% translate 'Filter by category:' %}
  {% for tag_item in tags %}
    {% if tag_item.name != tag_filter %}
      <a href="{{ request.path }}?tag={{ tag_item.name }}">{{ tag_item.name|upper }}</a>
    {% endif %}
  {% endfor %}
  </p>
{% endif %}
  <p><a href="{% url 'blog:post_authors' %}">{% translate 'List of authors' %}</a></p>
{% block article_archive %}
{% endblock article_archive %}
{% endblock content %}

blog/templates/blog/article_archive_year.html
{% extends 'blog/article_archive_tags.html' %}
{% load i18n %}

{% block title %}{{ website.acro }} | {% translate 'Articles' %} {{ year|date:"Y" }}{% endblock title %}
{% block article_archive %}
<h4><strong>
  {% translate 'Articles of' %} {{ year|date:"Y" }}
  {% if tag_filter %} {% translate 'in category:' %} {{ tag_filter|upper }}{% endif %}
</strong></h4>
{% include "blog/article_archive_list.html" %}
{% if is_paginated %}
  <nav aria-label="Page navigation container">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; {% translate 'PREVIOUS' %} </a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> {% translate 'NEXT' %} &raquo;</a></li>
    {% endif %}
  </ul>
  </nav>
{% endif %}
{% endblock article_archive %}

blog/templates/blog/article_detail.html
{% extends 'base.html' %}
{% load fb_versions %}
{% load i18n %}

{% block title %}{{ website.acro }} | {{ post.title }}{% endblock title %}

{% block content %}
    {% if images %}
      {% include 'pages/gallery.html' %}
    {% endif %}
      <div class="row row-striped">
        <div class="col-md-2"></div>
        <div class="col-md-10">
          <h3 class="text-uppercase"><strong>{{ post.title }}</strong></h3>
          <ul class="list-inline">
            {% if post.author %}
            <li class="list-inline-item">
              <i class="fa fa-user" aria-hidden="true"></i>
              {% if user.is_authenticated and post.author.is_active %}
              <a href="{% url 'contacts' %}?recipient={{ post.author }}&subject={{ post.title }}">
                {{ post.author.get_full_name }}</a>
              {% else %}
              {{ post.author.get_full_name }}
              {% endif %}
            </li>
            {% endif %}
            <li class="list-inline-item"><i class="fa fa-calendar-o" aria-hidden="true"></i> {{ post.date|date:"d M Y" }}</li>
            {% if post.get_tags %}
              <li class="list-inline-item">
                <i class="fa fa-folder-open" aria-hidden="true"></i>
                {% for tag in post.get_tags %}
                  <a href="{% url 'blog:post_index' %}?tag={{ tag }}">{{ tag|upper }}</a>
                {% endfor %}
              </li>
            {% endif %}
            {% if perms.blog.change_article %}
            <li class="list-inline-item">
              <i class="fa fa-pencil" aria-hidden="true"></i>
              <a href="/admin/blog/article/{{ post.uuid }}/change/">{% translate 'Modify' %}</a>
            </li>
            {% endif %}
          </ul>
          <p>{{ post.intro }}</p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          {{ post.body|safe }}
          <hr class="mb-4">
          {% if user.is_authenticated %}
            <div class="row">
              <h4 id="upload-anchor"><strong>{% translate 'Contributions' %}</strong></h4>
            </div>
            {% if perms.blog.add_userupload %}
              <div class="row">
                <a href="{% url 'blog:post_upload' %}?post_id={{ post.slug }}">
                {% translate 'Add a contribution' %}</a>
              </div>
            {% endif %}
            <hr class="mb-4">
            {% if post.get_uploads %}
            <div class="card-deck">
              {% for upload in post.get_uploads %}
                {% include 'blog/uploads.html' %}
              {% endfor %}
            </div>
            <hr class="mb-4">
            {% endif %}
          {% else %}
            <div class="row">
              <a href="{% url 'front_login' %}?next={{ request.get_full_path }}">{% translate 'Login' %}&nbsp;</a> {% translate 'if you want to add a contribution' %}
            </div>
            <hr class="mb-4">
          {% endif %}
          <div class="row">
            <div class="col col-6 text-left">
            {% with prev=post.get_previous %}{% if prev %}
              <i class="fa fa-arrow-left" aria-hidden="true"></i>
              <a href="{{ prev.get_path }}">{{ prev.title }}</a>
            {% endif %}{% endwith %}
            </div>
            <div class="col col-6 text-right">
              {% with next=post.get_next %}{% if next %}
              <a href="{{ next.get_path }}">{{ next.title }}</a>
              <i class="fa fa-arrow-right" aria-hidden="true"></i>
              {% endif %}{% endwith %}
            </div>
          </div>
        </div>
      </div>
{% endblock content %}

blog/templates/blog/article_pagination.html
{% load i18n %}

<nav aria-label="Page navigation container">
<ul class="pagination justify-content-center">
  {% if page_obj.has_previous %}
  <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; {% translate 'PREVIOUS' %} </a></li>
  {% endif %}
  {% if page_obj.has_next %}
  <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> {% translate 'NEXT' %} &raquo;</a></li>
  {% endif %}
</ul>
</nav>

blog/templates/blog/author_list.html
{% extends 'base.html' %}
{% load fb_versions %}
{% load i18n %}

{% block title %}{{ website.acro }} | {% translate 'Authors' %}{% endblock title %}

{% block content %}
<h4><strong>{% translate 'List of authors' %}</strong></h4>
<hr class="mb-4">
{% if authors %}
  {% with pass=user.is_authenticated %}
    {% for author, counts in authors.items %}
      <div class="row row-striped">
        <div class="col-md-2 text-center">
          {% if author.profile.avatar %}
          <img src="{% version author.profile.get_thumb 'admin_thumbnail' %}" class="rounded-circle">
          {% endif %}<h5>{{ author.get_full_name }}</h5>
        </div>
        <div class="col-md-8">
          {% translate "No biographical notes" as trans01 %}
          <p>{{ author.profile.bio|default_if_none:trans01 }}</p>
          <ul class="list-inline">
            {% if pass and counts.0 %}
              <li class="list-inline-item">
                <i class="fa fa-folder-open" aria-hidden="true"></i>
                  {% translate "Number of" %} <a href="{% url 'blog:post_by_author' author.username %}">{% translate "articles" %}</a>: {{ counts.0 }}
              </li>
            {% endif %}
            {% if pass and counts.1 %}
              <li class="list-inline-item">
                <i class="fa fa-upload" aria-hidden="true"></i>
                  {% translate "Number of" %} <a href="{% url 'blog:upload_by_author' author.username %}">{% translate "contributions" %}</a>: {{ counts.1 }}
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    {% endfor %}
  {% endwith %}
{% else %}
    <div class="col-md-12">
        <p>{% translate "No authors available." %}</p>
    </div>
{% endif %}
<hr class="mb-4">
{% if is_paginated %}
  {% include 'blog/article_pagination.html' %}
{% endif %}
{% endblock content %}

blog/templates/blog/uploads.html
{% load fb_versions %}
{% load i18n %}

<div class="card" style="margin-bottom: 20px; min-width: 18rem;">
    {% if upload.image %}
    <img class="card-img-top" src="{% version upload.image 'large' %}" width="100%" alt="" />
    {% endif %}
  <div class="card-body">
    <p class="card-text">{{ upload.body }}</p>
  </div>
  <div class="card-footer">
    {% if upload.user.profile.avatar %}
    <img src="{% version upload.user.profile.get_thumb 'admin_thumbnail' %}" width="32px" class="rounded-circle">
    {% endif %}
    {{ upload.user.get_full_name }}, {% translate 'uploaded on' %} {{ upload.date|date:"d M Y"}}
  </div>
</div>

blog/templates/blog/uploads_by_author.html
{% extends 'base.html' %}
{% load fb_versions %}
{% load i18n %}

{% block title %}{{ website.acro }} | {% translate 'Contributions by' %} {{ author.get_full_name }} {% endblock title %}
{% block content %}
<p><a href="{% url 'blog:post_authors' %}">{% translate 'List of authors' %}</a></p>
<h4><strong>
  {% translate 'Contributions by' %} {{ author.get_full_name }}
  {% if author.profile.avatar %}
  <img src="{% version author.profile.get_thumb 'admin_thumbnail' %}" class="rounded-circle">
  {% endif %}
</strong></h4>
  <div class="card-deck">
    {% for upload in uploads %}
    <div class="card" style="margin-bottom: 20px; min-width: 18rem;">
        {% if upload.image %}
        <img class="card-img-top" src="{% version upload.image 'large' %}" width="100%" alt="" />
        {% endif %}
      <div class="card-body">
        <p class="card-text">{{ upload.body }}</p>
      </div>
      <div class="card-footer">
        {% translate 'Uploaded on' %} {{ upload.date|date:"d M Y"}} in
          <a href="{{ upload.post.get_path }}">{{ upload.post.title }}</a>
      </div>
    </div>
    {% endfor %}
  </div>
{% if is_paginated %}
  {% include 'blog/article_pagination.html' %}
{% endif %}
{% endblock content %}

blog/templates/blog/userupload_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}{{ website.acro }} | {% translate 'Add contribution' %}{% endblock title %}

{% block content %}
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <h4><strong>{% translate 'Add a contribution' %}</strong></h4>
    <p>{% blocktranslate with name=user.get_short_name %}Hello {{ name }}, add here your contribution, then submit{% endblocktranslate %}.</p>
    <form action="" method="post" class="needs-validation" enctype="multipart/form-data" novalidate>
        <div class="row">
          <div class="col-md-9 mb-3">
            {{ form.image|as_crispy_field }}
          </div>
        </div>
        <div class="row">
          <div class="col-md-9 mb-3">
            {{ form.body|as_crispy_field }}
          </div>
        </div>
        {% include 'users/profile_includes/button.html' %}
      {% csrf_token %}
    </form>
  </div>
</div>
{% endblock content %}